package  com.nbk.insights.ui.screens

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.tooling.preview.Preview
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.navigation.NavController
import androidx.navigation.compose.rememberNavController
import com.nbk.insights.components.BottomNavigationBar
import com.nbk.insights.components.CardItem
import com.nbk.insights.components.TransactionItem
import com.nbk.insights.components.TotalBalanceCard
import com.nbk.insights.data.Transaction
import com.nbk.insights.data.BankCard
import com.nbk.insights.data.getRecentTransactions
import com.nbk.insights.data.getBankCards
import com.nbk.insights.ui.theme.insightsTheme